# Generated by Django 2.2.5 on 2019-09-28 15:39

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', djongo.models.fields.EmbeddedModelField(model_container=api.models.Book, null=True)),
            ],
        ),
    ]
